import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RegisterModal from "./components/modals/RegisterModal";
import GlobalError from "./global-error";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import ToasterProvider from "./providers/ToasterProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", 
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RegisterModal />
        <ToasterProvider />
        {/* <ErrorBoundary errorComponent={GlobalError}> */}
          {children}
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}
