import type { Metadata } from "next";
import "./globals.css";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "./components/navbar/Navbar";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
import { Nunito } from "next/font/google";


export const metadata: Metadata = {
  title: "airbnb",
  description: "Generated by create next app",
};
const font = Nunito({
  subsets: ['latin'],
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <RegisterModal />
        <LoginModal />
        <RentModal />
        <SearchModal />
        <ToasterProvider />
        <Navbar currentUser={currentUser} />
         {/* <Categories /> */}
        <div className="pb-20 pt-28">{children}</div>
        {/* <ErrorBoundary errorComponent={GlobalError}> */}
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}
